apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: ollama-
namespace: private

resources:
  - service-account.yaml
  - pvc.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml