apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: private
  labels:
    app: private-code-ollama
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: pv
  resources:
    requests:
      storage: 100Gi
