apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: auth-trauth
  namespace: dmz
spec:
  plugin:
    trauth:
      domain: ".dmz.home"
      # cookiename: "trauth_cookie"
      # cookiepath: "/"
      # cookiesecure: false   # set true if using HTTPS
      # cookiehttponly: true
      usersfile: "/etc/trauth-dmz/auth"