apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute
  namespace: default
  labels:
    app: main-technitium
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`technitium.main.home`)
      # middlewares:
      #   - name: main-middleware-auth-trauth
      services:
        - name: main-technitium-service
          port: 2283
  #tls: {} 

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-dos
  namespace: default
  labels:
    app: main-technitium
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`technitium.main.home`)
      # middlewares:
      #   - name: main-middleware-auth-trauth
      services:
        - name: main-technitium-service
          port: 2284
  #tls: {} 

---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-dohs
  namespace: default
  labels:
    app: main-technitium
spec:
  entryPoints:
    - websecure # dns-over-https3 dns-over-https2
  routes:
    - kind: Rule
      match: Host(`dns.technitium.main.home`) #/dns-query
      # middlewares:
      #   - name: set-real-ip
      services:
        - name: main-technitium-service-dns-192
          port: 443
  #tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-doh
  namespace: default
  labels:
    app: main-technitium
spec:
  entryPoints:
    - web # dns-over-http
  routes:
    - kind: Rule
      match: Host(`dns.technitium.main.home`) #/dns-query
      # middlewares:
      #   - name: set-real-ip
      services:
        - name: main-technitium-service-dns-192
          port: 80
  #tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-dohrp
  namespace: default
  labels:
    app: main-technitium
spec:
  entryPoints:
    - web # dns-over-http-rp
  routes:
    - kind: Rule
      match: Host(`dns.technitium.main.home`) #/dns-query
      # middlewares:
      #   - name: set-real-ip
      services:
        - name: main-technitium-service-dns-192
          port: 8053
  #tls: {}