apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: technitium-
namespace: default

resources:
  - pvc.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
- name: technitium-config
  envs:
  - config.env

generatorOptions:
  disableNameSuffixHash: false   # keep hashing for proper rollouts