apiVersion: v1
kind: PersistentVolume
metadata:
  name: technitium-pv
  namespace: default
  labels:
    app: main-technitium
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
    # - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.24  # your NFS server IP
    path: /bhole/cluster/default/technitium/ # your NFS export path