---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: default
  labels:
    app: main-technitium
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs
  volumeName: technitium-pv
  resources:
    requests:
      storage: 10Gi