# https://github.com/TechnitiumSoftware/DnsServer/blob/master/docker-compose.yml
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: default
  labels:
    app: main-technitium
spec:
  type: LoadBalancer
  selector:
    app: main-technitium
  ports:
    - name: dns-UDP
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-TCP
      port: 53
      targetPort: 53
      protocol: TCP
    - name: DNS-over-QUIC service
      port: 853
      targetPort: 853
      protocol: UDP
    - name: DNS-over-TLS service
      port: 853
      targetPort: 853
      protocol: TCP
    # - name : DNS-over-HTTPS service (HTTP/3)
    #   port: 443
    #   targetPort: 443
    #   protocol: UDP
    # - name : DNS-over-HTTPS service (HTTP/1.1, HTTP/2)
    #   port: 443
    #   targetPort: 443
    #   protocol: TCP
    # - name : DNS-over-HTTP service (use with reverse proxy or certbot certificate renewal)
    #   port: 80
    #   targetPort: 80
    #   protocol: TCP
    - name: DNS-over-HTTP service (use with reverse proxy)
      port: 8053
      targetPort: 8053
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: service-dashboard
  namespace: default
  labels:
    app: main-technitium
spec:
  type: ClusterIP
  selector:
    app: main-technitium
  ports:
    - name: http-web
      port: 5380
      targetPort: 2283
    - name: https-web
      port: 53443
      targetPort: 2283
