apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-pvc
  namespace: dmz
  labels:
    app: dmz-media
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs
  volumeName: media-pv
  resources:
    requests:
      storage: 250Gi