apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-basic-auth
  namespace: default
spec:
  basicAuth:
    secret: dmz-media-media-basic-auth-secret
    realm: "dmz-media-middleware-basic-auth"