apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
  namespace: dmz
  labels:
    app: dmz-media
spec:
  capacity:
    storage: 250Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # cephfs
  # mountOptions:
  #   - nolock
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeHandle: cephfs-vicus-dmz-media-stack
    volumeAttributes:
      clusterID: rook-ceph
      fsName: bhole
      staticVolume: "true"
      rootPath: /volumes/colosseum/vicus-dmz/08622c4f-fd51-4c77-8d1c-9a5d3c6e6d66/media-stack/
