apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: private
  labels:
    app: private-homeassistant
spec:
  type: ClusterIP
  selector:
    app: private-homeassistant
  ports:
    - name: web
      protocol: TCP
      port: 4404
      targetPort: 8123