apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod-dmz
resources:
  - ../../../base/dmz
patches:
  - target:
      kind: .* # applies to all kinds
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: prod-dmz
