apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: main-
namespace: default

resources:
  - middleware
  - openwrt
  - traefik
  - technitium
  - harbor
  - authentik
  - glance
  - gatus
  - dozzle

secretGenerator:
  - name: auth-basic-secret
    envs:
    - secret.env
    type: Opaque

# secretGenerator:
#   - name: public-auth-basic-secret
#     envs:
#     - secret.env
#     type: Opaque
# 
# secretGenerator:
#   - name: private-auth-basic-secret
#     envs:
#     - secret.env
#     type: Opaque
# 
# secretGenerator:
#   - name: dmz-auth-basic-secret
#     envs:
#     - secret.env
#     type: Opaque
# 
# secretGenerator:
#   - name: dmz-media-auth-basic-secret
#     envs:
#     - secret.env
#     type: Opaque

generatorOptions:
  disableNameSuffixHash: true