apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - middleware-basic-auth.yaml
  # - middleware-auth-sso.yaml
  - traefik
  - technitium

secretGenerator:
  - name: main-basic-auth-secret
    envs:
    - secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true