apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - middleware-auth-basic.yaml
  - middleware-auth-trauth.yaml
  - middleware-auth-authentik.yaml
  - traefik
  - technitium

secretGenerator:
  - name: main-auth-basic-secret
    envs:
    - secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true