apiVersion: v1
kind: Pod
metadata:
  name: test-net-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: net-a,net-b
spec:
  containers:
  - name: test
    image: nicolaka/netshoot
    command: ["sleep", "infinity"]