apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: default
  labels:
    app: main-<app-name>
spec:
  capacity:
    storage: <app-cap>Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # cephfs
  # mountOptions:
  #   - nolock
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeHandle: cephfs-vicus-default-<app-name>
    volumeAttributes:
      clusterID: rook-ceph   
      fsName: bhole
      staticVolume: "true"
      rootPath: /volumes/k8s-colosseum/vicus-default/daeef6bb-d993-4383-86af-2745a851bf55/<app-name>/
