apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: middleware-
namespace: default

resources:
  - auth-basic.yaml
  - auth-trauth.yaml
  - auth-authentik.yaml
  - redirect-https.yaml
  # - redirect