apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: main-
namespace: default

resources:
  - middleware-auth-basic.yaml
  - middleware-auth-trauth.yaml
  - middleware-auth-authentik.yaml
  - middleware-redirect-https
  # - redirect