apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-auth-basic
  namespace: default
spec:
  basicAuth:
    secret: main-auth-basic-secret
    realm: "main-middleware-auth-basic"