apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: qbittorrent-
namespace: dmz

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

# secretGenerator:
# - name: gluetun-secrets
#   envs:
#   - secret.env