apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: <app-ns>
  labels:
    app: <app-ns>-<app-name>
spec:
  type: ClusterIP
  selector:
    app: <app-ns>-<app-name>
  ports:
    - name: web
      protocol: TCP
      port: 6680 # port of that service
      targetPort: 80 # port of the container
    - name: websecure
      protocol: TCP
      port: 6680
      targetPort: 443

---
apiVersion: v1
kind: Service
metadata:
  name: service-lb
  namespace: <app-ns>
  labels:
    app: <app-ns>-<app-name>
  annotations:
    metallb.io/address-pool: internal-ips
    # metallb.io/loadBalancerIPs: 192.168.1.1
spec:
  type: LoadBalancer
  selector:
    app: <app-ns>-<app-name>
  # loadBalancerIP: 192.168.1.1 # deprecated do annotations
  # externalTrafficPolicy: Local # keep src ip , but if node doesn't run pod then drop traffic ...
  ports:
    - name: web-lb
      protocol: TCP
      port: 6680
      targetPort: 80
    - name: websecure-lb
      protocol: TCP
      port: 6643
      targetPort: 443
