apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: dmz
  labels:
    app: dmz-media-readarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmz-media-readarr
  template:
    metadata:
      labels:
        app: dmz-media-readarr
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      # Ensure PostgreSQL user (uid 70) can write to PVC
      securityContext:
        fsGroup: 70
      
      initContainers:
        # --- postgres sidecar ---
        - name: postgres
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          # Setting restartPolicy: Always makes this a sidecar container.
          restartPolicy: Always
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DATABASE
              value: "readarr-glasses"
            - name: POSTGRES_USER
              value: "readarr-glasses"
          envFrom:
            - secretRef:
                name: readarr-secret
          volumeMounts:
            - name: media-storage
              mountPath: /var/lib/postgresql
              subPath: readarr/pgdata
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - readarr-glasses
            initialDelaySeconds: 5
            periodSeconds: 2

      containers:
        - name: readarr
          image: blampe/rreading-glasses:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          command: ["/main", "serve"]
          args:
            - "--upstream=www.goodreads.com"
          env:
            - name: POSTGRES_HOST
              value: "127.0.0.1"
            - name: POSTGRES_DATABASE
              value: "readarr-glasses"
            - name: POSTGRES_USER
              value: "readarr-glasses"
          envFrom:
            - secretRef:
                name: readarr-secret
          ports:
            - containerPort: 8787
              name: web
          volumeMounts:
            - name: media-storage
              mountPath: /config
              subPath: readarr/config
            - name: media-storage
              mountPath: /books
              subPath: media/books
            - name: media-storage
              mountPath: /downloads
              subPath: downloads/readarr

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName:  media-pvc