---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: private
  labels:
    app: private-dozzle
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs
  volumeName: dozzle-pv
  resources:
    requests:
      storage: 1Gi