apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: private
  labels:
    app: private-dozzle
spec:
  type: ClusterIP
  selector:
    app: private-dozzle
  ports:
    - name: web
      protocol: TCP
      port: 4415
      targetPort: 8080