apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
  labels:
    app: main-authentik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-authentik
  template:
    metadata:
      labels:
        app: main-authentik
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      serviceAccountName: serviceaccount
      # Ensure PostgreSQL user (uid 70) can write to PVC
      securityContext:
        fsGroup: 70
      initContainers:
        # --- PostgreSQL sidecar ---
        - name: postgres
          image: postgres:alpine
          imagePullPolicy: IfNotPresent
          # Setting restartPolicy: Always makes this a sidecar container.
          restartPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: authentik-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-secret
                  key: AUTHENTIK_POSTGRESQL__PASSWORD
          securityContext:
            capabilities:
              add:
                - CHOWN
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
              subPath: pgdata
          # Health check for PostgreSQL
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - authentik
            initialDelaySeconds: 5
            periodSeconds: 2
        # --- valkey sidecar ---
        - name: valkey
          image: valkey/valkey:alpine
          imagePullPolicy: IfNotPresent
          # Setting restartPolicy: Always makes this a sidecar container.
          restartPolicy: Always
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - valkey-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 2
      containers:
        # --- Authentik Server ---
        - name: authentik-server
          image: ghcr.io/goauthentik/server:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          args:
            - server
          ports:
            - containerPort: 9000 # HTTP
            - containerPort: 9443 # HTTPS
          envFrom:
            - configMapRef:
                name: authentik-config
            - secretRef:
                name: authentik-secret
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: data
            - name: data
              mountPath: /custom-templates
              subPath: custom-templates
          livenessProbe:
            httpGet:
              path: /-/health/live/
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/health/ready/
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 5
        # --- Authentik Worker ---
        - name: authentik-worker
          image: ghcr.io/goauthentik/server:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          args:
            - worker
          envFrom:
            - configMapRef:
                name: authentik-config
            - secretRef:
                name: authentik-secret
          volumeMounts:
            - name: data
              mountPath: /data
              subPath: data
            - name: data
              mountPath: /certs
              subPath: certs
            - name: data
              mountPath: /custom-templates
              subPath: custom-templates
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
