apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: searxng-
namespace: dmz
resources:
  - sa.yaml
  - pv-cephfs.yaml
  - pvc-cephfs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: searxng-settings
    files:
      - settings.yaml
secretGenerator:
  - name: searxng-secret
    envs:
      - secret.env
    type: Opaque
