apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: default
  labels:
    app: main-traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-traefik
  template:
    metadata:
      labels:
        app: main-traefik
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      serviceAccountName: serviceaccount
      containers:
        - name: traefik
          image: traefik:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          args:
            - --api
            - --api.dashboard
            - --api.insecure
            - --entrypoints.web.address=:80
            - --entrypoints.websecure.address=:443
            # - --entrypoints.web.http.redirections.entrypoint.to=websecure
            # - --entrypoints.web.http.redirections.entrypoint.scheme=https
            # - --entrypoints.web.http.redirections.entrypoint.permanent=true
            - --providers.kubernetescrd
            - --providers.kubernetescrd.allowCrossNamespace=true
            - --providers.kubernetescrd.allowexternalnameservices=true
            - --metrics.prometheus.entryPoint=metrics
            - --entrypoints.metrics.address=:8082
            - --tracing=true
            - --accesslog
            - --experimental.plugins.trauth.moduleName=github.com/leonjza/trauth
            - --experimental.plugins.trauth.version=v1.6.5
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
            - name: metrics
              containerPort: 8082
          volumeMounts:
            - name: trauth-secret-main
              mountPath: /etc/trauth-main
            - name: trauth-secret-main
              mountPath: /etc/trauth-private
            - name: trauth-secret-main
              mountPath: /etc/trauth-public
            - name: trauth-secret-main
              mountPath: /etc/trauth-dmz
            - name: trauth-secret-main # no cross namespace
              mountPath: /etc/trauth-dmz-media
      volumes:
      - name: trauth-secret-main
        secret:
          secretName: main-auth-basic-secret
      # - name: trauth-secret-private
      #   secret:
      #     secretName: private-auth-basic-secret
      # - name: trauth-secret-public
      #   secret:
      #     secretName: public-auth-basic-secret
      # - name: trauth-secret-dmz
      #   secret:
      #     secretName: dmz-auth-basic-secret
      # - name: trauth-secret-dmz-media
      #   secret:
      #     secretName: dmz-media-auth-basic-secret
