apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: private-


resources:
  - middleware-basic-auth.yaml
  # - middleware-auth-sso.yaml
  # - redirect
  - dozzle
  - glance
  - gatus
  # - k8sdashboard
  # - home-assistant
  # - ollama
  # - webui

secretGenerator:
  - name: basic-auth-secret
    envs:
    - secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true