apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: private-
namespace: private

resources:
  - middleware
  - glance
  - gatus
  - monitor
  - code
  - home
  - feed
  - tools

secretGenerator:
  - name: auth-basic-secret
    envs:
    - secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true