apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-basic-auth
  namespace: default
spec:
  basicAuth:
    secret: basic-auth-secret
    realm: "public-middleware-basic-auth"