apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: middleware-auth-sso
  namespace: prod-public
spec:
  plugin:
    trauth:
      domain: ".public.home"
      # cookiename: "trauth_cookie"
      # cookiepath: "/"
      # cookiesecure: false   # set true if using HTTPS
      # cookiehttponly: true
      usersfile: "/etc/trauth/auth"