storage:
  type: sqlite
  path: /data/data.db

metrics: true

endpoints:
  - name: glance
    url: "http://dmz-glance-service.prod-dmz.svc.cluster.local:6600"
    interval: 30s
    conditions:
      - "[STATUS] == 200"