apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: forgejo-
namespace: dmz
resources:
  - sa.yaml
  - pv-cephfs.yaml
  - pvc-cephfs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
