apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: dmz
  labels:
    app: dmz-oss-forgejo
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.24
    path: /bhole/cluster/dmz/oss/forgejo/
