apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: dmz
  labels:
    app: dmz-oss-forgejo
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs
  volumeName: pv
  resources:
    requests:
      storage: 100Gi