apiVersion: v1
kind: PersistentVolume
metadata:
  name: dozzle-pv
  namespace: private
  labels:
    app: private-dozzle
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
    # - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.24  # your NFS server IP
    path: /bhole/cluster/private/dozzle/ # your NFS export path