storage:
  type: sqlite
  path: /data/data.db

metrics: true

endpoints:
  - name: dozzle
    url: "http://dozzle.public.home" # .svc.cluster:SVC PORT
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  
  - name: glance
    url: "http://glance.public.home"
    interval: 30s
    conditions:
      - "[STATUS] == 200"