apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: private
  labels:
    app: private-gatus
spec:
  type: ClusterIP
  selector:
    app: private-gatus
  ports:
    - name: web
      protocol: TCP
      port: 4401
      targetPort: 8080