apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  calicoNetwork:
    containerIPForwarding: Enabled
    ipPools:
      - name: default-ipv4-ippool
        cidr: 10.42.0.0/16
        encapsulation: VXLAN
        natOutgoing: Enabled