pages:
  - name: public
    columns:
      - size: full
        widgets:
          - type: bookmarks
            groups:
              - title: Public Services
                links:
                  - title: Public Gatus
                    url: http://gatus.public.home
                    description: Public monitoring
