apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: <app-ns>
  labels:
    app: <app-ns>-<app-name>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <app-ns>-<app-name>
  template:
    metadata:
      labels:
        app: <app-ns>-<app-name>
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      serviceAccountName: serviceaccount
      containers:
        - name: <app-name>
          image: <app-URL>:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          envFrom:
            - configMapRef:
                name: youtarr-config
            - secretRef:
                name: youtarr-secret
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: data
              mountPath: /opt/adguardhome/work
              subPath: work
            - name: data
              mountPath: /opt/adguardhome/conf
              subPath: conf
              # readinessProbe:
              #   httpGet:
              #     path: /
              #     port: 80
              #   initialDelaySeconds: 5
              #   periodSeconds: 10
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
