apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: <app-ns>
  labels:
    app: <app-ns>-<app-name>
spec:
  accessModes: [ReadWriteMany]
  storageClassName: nfs
  volumeName: pv
  resources:
    requests:
      storage: <app-cap>Gi