apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: prometheus-
namespace: private

resources:
  - pvc.yaml
  - pv.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yaml