apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: piped-
namespace: dmz
resources:
  - sa.yaml
  - pvc-cephfs.yaml
  - pv-cephfs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: piped-config
    envs:
      - config.env
secretGenerator:
  - name: piped-secret
    envs:
      - secret.env
    files:
      - config.properties=config_properties.env
    type: Opaque
