"""Auto-generated by scan.py — do not edit manually."""
import model as m

tree = m.Tree()

# ══════ main (default ns) ══════

tree.main.app(
    name="TEST_TLS",
    containers=[],
    options=m.Options(service=False, ingress=False),
)

tree.main.app(
    name="authentik",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="10Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="valkey/valkey:alpine",
            name="valkey",
            ports=[m.Port(number=6379)],
        ),
        m.Container(
            image="ghcr.io/goauthentik/server:latest",
            name="authentik-server",
            ports=[
                m.Port(number=9000, service_port=2288),
                m.Port(number=9443, service_port=2289),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/data",
                    size="10Gi",
                    sub_path="data",
                ),
                m.Volume(
                    name="data",
                    at="/custom-templates",
                    size="10Gi",
                    sub_path="custom-templates",
                ),
            ],
        ),
        m.Container(
            image="ghcr.io/goauthentik/server:latest",
            name="authentik-worker",
            mounts=[
                m.Volume(
                    name="data",
                    at="/data",
                    size="10Gi",
                    sub_path="data",
                ),
                m.Volume(
                    name="data",
                    at="/certs",
                    size="10Gi",
                    sub_path="certs",
                ),
                m.Volume(
                    name="data",
                    at="/custom-templates",
                    size="10Gi",
                    sub_path="custom-templates",
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="authentik.main.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(verbs=["get", "list", "watch"], resources=["*"]),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["rbac.authorization.k8s.io"],
                resources=["*"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["apiextensions.k8s.io"],
                resources=["customresourcedefinitions", "*"],
            ),
        ],
    ),
)

tree.main.app(
    name="dozzle",
    containers=[
        m.Container(
            image="amir20/dozzle:latest",
            ports=[
                m.Port(number=8080, service_port=2215),
            ],
            mounts=[
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
            env={
                "DOZZLE_MODE": "k8s",
                "DOZZLE_ALL_NAMESPACES": "true",
                "DOZZLE_LEVEL": "info",
            },
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="dozzle.main.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                resources=["pods", "pods/log", "nodes"],
            ),
            m.PolicyRule(
                verbs=["get", "list"],
                api_groups=["metrics.k8s.io"],
                resources=["pods"],
            ),
        ],
    ),
)

tree.main.app(
    name="gatus",
    containers=[
        m.Container(
            image="twinproduction/gatus:latest",
            ports=[
                m.Port(number=8080, service_port=2201),
            ],
            mounts=[
                m.Config(
                    name="gatus-config",
                    at="/config",
                    file="config.yaml",
                    ro=False,
                ),
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="gatus.main.home"),
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=2200),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="glance.main.home"),
)

tree.main.app(
    name="harbor",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="100Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="valkey/valkey:alpine",
            name="valkey",
            ports=[m.Port(number=6379)],
        ),
        m.Container(
            image="goharbor/harbor-core:v2.15.2",
            name="core",
            ports=[
                m.Port(number=8080, service_port=2290),
                m.Port(number=8443, service_port=2291),
                m.Port(number=8085, service_port=2294),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/data",
                    size="100Gi",
                    sub_path="core-data",
                ),
                m.Volume(
                    name="data",
                    at="/etc/core/ca",
                    size="100Gi",
                    sub_path="ca_download",
                ),
                m.Config(
                    name="core-config",
                    at="/etc/core/app.conf",
                    file="config.yaml",
                    ro=False,
                ),
                m.SecretMount(
                    name="harbor-core-private-key",
                    at="/etc/core/private_key.pem",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="harbor-core-secretkey",
                    at="/etc/core/key",
                    env_file="secret.env",
                    ro=False,
                ),
            ],
        ),
        m.Container(
            image="goharbor/registry-photon:v2.15.2",
            name="registry",
            ports=[m.Port(number=5000)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/storage",
                    size="100Gi",
                    sub_path="registry",
                ),
                m.Config(
                    name="registry-config",
                    at="/etc/registry/config.yml",
                    file="config.yaml",
                    ro=False,
                ),
                m.SecretMount(
                    name="harbor-registry-root-crt",
                    at="/etc/registry/root.crt",
                    env_file="secret.env",
                    ro=False,
                ),
            ],
        ),
        m.Container(
            image="goharbor/harbor-registryctl:v2.15.2",
            name="registryctl",
            ports=[m.Port(number=8081)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/storage",
                    size="100Gi",
                    sub_path="registry",
                ),
                m.Config(
                    name="registry-config",
                    at="/etc/registry/config.yml",
                    file="config.yaml",
                    ro=False,
                ),
                m.Config(
                    name="registryctl-config",
                    at="/etc/registryctl/config.yml",
                    file="config.yaml",
                    ro=False,
                ),
            ],
            env={
                "CONFIG_PATH": "/etc/registryctl/config.yml",
                "REGISTRY_CONFIG": "/etc/registry/config.yml",
            },
        ),
        m.Container(
            image="goharbor/harbor-portal:v2.15.2",
            name="portal",
            ports=[
                m.Port(number=8090, service_port=2293),
            ],
            mounts=[
                m.Config(
                    name="portal-config",
                    at="/etc/nginx/nginx.conf",
                    file="config.yaml",
                    ro=False,
                ),
            ],
        ),
        m.Container(
            image="goharbor/harbor-jobservice:v2.15.2",
            name="jobservice",
            ports=[m.Port(number=8082)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/log/jobs",
                    size="100Gi",
                    sub_path="job_logs",
                ),
                m.Config(
                    name="jobservice-config",
                    at="/etc/jobservice/config.yml",
                    file="config.yaml",
                    ro=False,
                ),
            ],
            env={"CONFIG_PATH": "/etc/jobservice/config.yml"},
        ),
        m.Container(
            image="goharbor/trivy-adapter-photon:v2.15.2",
            name="trivy-adapter",
            ports=[m.Port(number=8083)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/home/scanner/.cache/trivy",
                    size="100Gi",
                    sub_path="trivy-adapter/trivy",
                ),
                m.Volume(
                    name="data",
                    at="/home/scanner/.cache/reports",
                    size="100Gi",
                    sub_path="trivy-adapter/reports",
                ),
            ],
        ),
        m.Container(
            image="goharbor/harbor-log:v2.15.2",
            name="log",
            ports=[
                m.Port(number=1514, service_port=2292),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/log/docker",
                    size="100Gi",
                    sub_path="logs",
                ),
                m.Config(
                    name="log-config",
                    at="/etc/logrotate.d/logrotate.conf",
                    file="config.yaml",
                    ro=False,
                ),
                m.Config(
                    name="log-config",
                    at="/etc/rsyslog.d/rsyslog_docker.conf",
                    file="config.yaml",
                    ro=False,
                ),
            ],
        ),
        m.Container(
            image="goharbor/harbor-exporter:v2.15.2",
            name="exporter",
            ports=[m.Port(number=8001)],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="harbor.main.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                resources=["pods", "namespaces", "*"],
            ),
        ],
    ),
)

tree.main.app(
    name="traefik",
    containers=[
        m.Container(
            image="traefik:latest",
            ports=[
                m.Port(number=80, name="web"),
                m.Port(number=443, name="websecure"),
                m.Port(number=8080, name="dashboard", service_port=2215),
                m.Port(number=8082, name="metrics", service_port=2282),
            ],
            mounts=[
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-main",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-private",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-public",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-dmz",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-dmz-media",
                    env_file="secret.env",
                    ro=False,
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="traefik.main.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                resources=["services", "endpoints", "secrets", "*"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["discovery.k8s.io"],
                resources=["endpointslices"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["extensions", "networking.k8s.io"],
                resources=["ingresses", "ingressclasses"],
            ),
            m.PolicyRule(
                verbs=["update"],
                api_groups=["extensions"],
                resources=["ingresses/status"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["traefik.io"],
                resources=[
                    "middlewares",
                    "middlewaretcps",
                    "ingressroutes",
                    "traefikservices",
                    "ingressroutetcps",
                    "ingressrouteudps",
                    "tlsoptions",
                    "tlsstores",
                    "serverstransports",
                    "serverstransporttcps",
                ],
            ),
            m.PolicyRule(
                verbs=["get", "list"],
                api_groups=["metrics.k8s.io"],
                resources=["pods"],
            ),
        ],
    ),
)

tree.main.app(
    name="middleware",
    containers=[],
    options=m.Options(service=False, ingress=False),
)

tree.main.app(
    name="netboot",
    containers=[
        m.Container(
            image="netbootxyz/netboot:latest",
            ports=[
                m.Port(number=69),
                m.Port(number=80, service_port=2203),
                m.Port(number=443, service_port=2204),
            ],
            mounts=[
                m.Volume(name="data", at="/config", size="100Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
)

tree.main.app(
    name="node-exporter",
    containers=[
        m.Container(
            image="ghcr.io/prometheus/node-exporter:master-distroless",
            name="main-node-exporter",
            ports=[m.Port(number=9100)],
            mounts=[
                m.Volume(
                    name="proc",
                    at="/host/proc",
                    ro=True,
                    host_path="/proc",
                ),
                m.Volume(
                    name="sys",
                    at="/host/sys",
                    ro=True,
                    host_path="/sys",
                ),
                m.Volume(
                    name="root",
                    at="/host/root",
                    ro=True,
                    host_path="/",
                ),
            ],
        ),
    ],
    kind="DaemonSet",
    options=m.Options(ingress=False),
    tolerations=[{"operator": "Exists"}],
)

tree.main.app(
    name="openwrt",
    containers=[
        m.Container(
            image="openwrt/rootfs:latest",
            ports=[
                m.Port(number=80, service_port=2240),
                m.Port(number=443, service_port=2243),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="openwrt.main.home"),
)


tree.main.folder("technitium").app(
    name="cert",
    containers=[],
    options=m.Options(service=False, ingress=False),
)

tree.main.app(
    name="technitium",
    containers=[
        m.Container(
            image="technitium/dns-server:latest",
            name="dns-server",
            ports=[
                m.Port(number=5380, service_port=2283),
                m.Port(number=53443, service_port=2284),
                m.Port(number=53, proto="UDP"),
                m.Port(number=53),
                m.Port(number=853, proto="UDP"),
                m.Port(number=853),
                m.Port(number=443, proto="UDP"),
                m.Port(number=443),
                m.Port(number=80),
                m.Port(number=8053),
            ],
            mounts=[
                m.Volume(name="config", at="/etc/dns", size="10Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="technitium.main.home"),
)

tree.main.app(
    name="ns>-<app-name>",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    storage="none",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="valkey/valkey:alpine",
            name="valkey",
            ports=[m.Port(number=6379)],
        ),
        m.Container(
            image="<app-URL>:latest",
            name="<app-name>",
            ports=[
                m.Port(number=53, proto="UDP"),
                m.Port(number=80, service_port=6680),
                m.Port(number=443, service_port=6643),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/opt/adguardhome/work",
                    storage="none",
                    sub_path="work",
                ),
                m.Volume(
                    name="data",
                    at="/opt/adguardhome/conf",
                    storage="none",
                    sub_path="conf",
                ),
            ],
            cpu="500m",
            mem="1Gi",
        ),
    ],
    replicas=2,
    options=m.Options(hpa=True),
    ingress=m.Ingress(host="<app-name>.<app-ns>.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(verbs=["get", "list", "watch"], resources=["*"]),
        ],
    ),
)

tree.main.app(
    name="ns>-<app-name>",
    containers=[
        m.Container(
            image="<app-URL>:latest",
            name="<app-name>",
            ports=[
                m.Port(number=80, service_port=6680),
                m.Port(number=443, service_port=6680),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/opt/adguardhome/work",
                    size="<app-cap>Gi",
                    storage="nfs",
                    sub_path="work",
                ),
                m.Volume(
                    name="data",
                    at="/opt/adguardhome/conf",
                    size="<app-cap>Gi",
                    storage="nfs",
                    sub_path="conf",
                ),
            ],
        ),
    ],
    options=m.Options(storage="nfs"),
    ingress=m.Ingress(host="<app-name>.<app-ns>.home"),
)

tree.main.app(
    name="traefik",
    containers=[
        m.Container(
            image="traefik:latest",
            ports=[
                m.Port(number=80, name="web"),
                m.Port(number=443, name="websecure"),
                m.Port(number=8080, name="dashboard", service_port=2280),
                m.Port(number=8082, name="metrics", service_port=2282),
            ],
            mounts=[
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-main",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-private",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-public",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-dmz",
                    env_file="secret.env",
                    ro=False,
                ),
                m.SecretMount(
                    name="main-auth-basic-secret",
                    at="/etc/trauth-dmz-media",
                    env_file="secret.env",
                    ro=False,
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="traefik.main.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                resources=["services", "endpoints", "secrets", "*"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["discovery.k8s.io"],
                resources=["endpointslices"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["extensions", "networking.k8s.io"],
                resources=["ingresses", "ingressclasses"],
            ),
            m.PolicyRule(
                verbs=["update"],
                api_groups=["extensions"],
                resources=["ingresses/status"],
            ),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=["traefik.io"],
                resources=[
                    "middlewares",
                    "middlewaretcps",
                    "ingressroutes",
                    "traefikservices",
                    "ingressroutetcps",
                    "ingressrouteudps",
                    "tlsoptions",
                    "tlsstores",
                    "serverstransports",
                    "serverstransporttcps",
                ],
            ),
            m.PolicyRule(
                verbs=["get", "list"],
                api_groups=["metrics.k8s.io"],
                resources=["pods"],
            ),
        ],
    ),
)
