"""Auto-generated by scan.py — do not edit manually."""
import model as m

tree = m.Tree()

# ══════ main (default ns) ══════


tree.main.folder("alternative-frontends").app(
    name="frontalt-invidious",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="10Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="quay.io/invidious/invidious-companion:latest",
            name="companion",
            ports=[
                m.Port(number=8282, service_port=6626),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/tmp/youtubei.js",
                    size="10Gi",
                    sub_path="companion-cache",
                ),
            ],
        ),
        m.Container(
            image="quay.io/invidious/invidious:latest",
            name="invidious",
            ports=[
                m.Port(number=3000, service_port=6625),
            ],
            mounts=[
                m.SecretMount(
                    name="invidious-config",
                    at="/invidious/config/config.yml",
                    env_file="secret.env",
                ),
            ],
            env={"CONFIG_FILE": "/invidious/config/config.yml"},
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="invidious.alt.dmz.home"),
)

tree.main.folder("alternative-frontends").app(
    name="frontalt-piped",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="10Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="1337kavin/piped:latest",
            name="backend",
            ports=[
                m.Port(number=8080, service_port=6629),
            ],
            mounts=[
                m.SecretMount(
                    name="piped-secret",
                    at="/app/config.properties",
                    env_file="secret.env",
                ),
            ],
        ),
        m.Container(
            image="1337kavin/piped-proxy:latest",
            name="proxy",
            ports=[
                m.Port(number=8080, service_port=6629),
            ],
        ),
        m.Container(
            image="1337kavin/piped-frontend:latest",
            name="frontend",
            ports=[m.Port(number=80, service_port=6627)],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="piped-api.alt.dmz.home"),
)

tree.main.folder("alternative-frontends").app(
    name="frontalt-searxng",
    containers=[
        m.Container(
            image="searxng/searxng:latest",
            name="searxng",
            ports=[
                m.Port(number=8888, service_port=6624),
            ],
            mounts=[
                m.Config(
                    name="searxng-settings",
                    at="/etc/searxng/settings.yml",
                    file="settings.yaml",
                    ro=False,
                ),
                m.Volume(name="data", at="/var/cache/searxng", size="10Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="searxng.alt.dmz.home"),
)

tree.main.app(
    name="frontalt-invidious",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="10Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="quay.io/invidious/invidious-companion:latest",
            name="companion",
            ports=[
                m.Port(number=8282, service_port=6626),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/tmp/youtubei.js",
                    size="10Gi",
                    sub_path="companion-cache",
                ),
            ],
        ),
        m.Container(
            image="quay.io/invidious/invidious:latest",
            name="invidious",
            ports=[
                m.Port(number=3000, service_port=6625),
            ],
            mounts=[
                m.SecretMount(
                    name="invidious-config",
                    at="/invidious/config/config.yml",
                    env_file="secret.env",
                ),
            ],
            env={"CONFIG_FILE": "/invidious/config/config.yml"},
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="invidious.alt.dmz.home"),
)


tree.main.folder("cloud").app(
    name="cloud-immich",
    containers=[
        m.Container(
            image="ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="128Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="valkey/valkey:alpine",
            name="valkey",
            ports=[m.Port(number=6379)],
        ),
        m.Container(
            image="ghcr.io/immich-app/immich-machine-learning:release",
            name="machine-learning",
            ports=[m.Port(number=3003)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/cache",
                    size="128Gi",
                    sub_path="ml-cache",
                ),
            ],
            cpu="500m",
            mem="1Gi",
        ),
        m.Container(
            image="ghcr.io/immich-app/immich-server:release",
            name="immich-server",
            ports=[
                m.Port(number=2283, service_port=6604),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/data",
                    size="128Gi",
                    sub_path="library",
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="immich.alt.dmz.home"),
)

tree.main.app(
    name="cloud-immich",
    containers=[
        m.Container(
            image="ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/var/lib/postgresql",
                    size="128Gi",
                    sub_path="pgdata",
                ),
            ],
        ),
        m.Container(
            image="valkey/valkey:alpine",
            name="valkey",
            ports=[m.Port(number=6379)],
        ),
        m.Container(
            image="ghcr.io/immich-app/immich-machine-learning:release",
            name="machine-learning",
            ports=[m.Port(number=3003)],
            mounts=[
                m.Volume(
                    name="data",
                    at="/cache",
                    size="128Gi",
                    sub_path="ml-cache",
                ),
            ],
            cpu="500m",
            mem="1Gi",
        ),
        m.Container(
            image="ghcr.io/immich-app/immich-server:release",
            name="immich-server",
            ports=[
                m.Port(number=2283, service_port=6604),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/data",
                    size="128Gi",
                    sub_path="library",
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="immich.alt.dmz.home"),
)

tree.main.app(
    name="game",
    containers=[],
    options=m.Options(service=False, ingress=False),
)

tree.main.app(
    name="gatus",
    containers=[
        m.Container(
            image="twinproduction/gatus:latest",
            ports=[
                m.Port(number=8080, service_port=6601),
            ],
            mounts=[
                m.Config(
                    name="gatus-config",
                    at="/config",
                    file="config.yaml",
                    ro=False,
                ),
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=6600),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=6601),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(
        host="glance.dmz.home",
        auth="dmz-middleware-auth-basic",
    ),
)


tree.main.folder("media").app(
    name="media-autobrr",
    containers=[
        m.Container(
            image="ghcr.io/autobrr/autobrr:latest",
            name="autobrr",
            ports=[
                m.Port(number=7474, name="web", service_port=6665),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="autobrr/config",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="autobrr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-bazarr",
    containers=[
        m.Container(
            image="lscr.io/linuxserver/bazarr:latest",
            name="bazarr",
            ports=[
                m.Port(number=6767, name="web", service_port=6664),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="bazarr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/movies",
                    storage="none",
                    sub_path="media/movies",
                ),
                m.Volume(
                    name="media-storage",
                    at="/tv",
                    storage="none",
                    sub_path="media/tv",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="bazarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-jellyfin",
    containers=[
        m.Container(
            image="ghcr.io/jellyfin/jellyfin:latest",
            name="jellyfin",
            ports=[
                m.Port(number=8096, name="web", service_port=6650),
                m.Port(number=8920, name="websecure", service_port=6651),
                m.Port(number=7359, name="dlna"),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="jellyfin/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/cache",
                    storage="none",
                    sub_path="jellyfin/cache",
                ),
                m.Volume(
                    name="media-storage",
                    at="/data/media",
                    storage="none",
                    sub_path="media",
                ),
            ],
            env={"DOTNET_USE_POLLING_FILE_WATCHER": "1"},
        ),
    ],
    ingress=m.Ingress(host="jellyfin.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-jellyseerr",
    containers=[
        m.Container(
            image="fallenbagel/jellyseerr:latest",
            name="jellyseerr",
            ports=[
                m.Port(number=5055, name="web", service_port=6660),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/app/config",
                    storage="none",
                    sub_path="jellyseerr/config",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="jellyseerr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-jellystat",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/var/lib/postgresql",
                    storage="none",
                    sub_path="jellystat/pgdata",
                ),
            ],
        ),
        m.Container(
            image="ghcr.io/cyfershepard/jellystat:latest",
            name="jellystat",
            ports=[
                m.Port(number=3001, name="web", service_port=6666),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/app/backend/data",
                    storage="none",
                    sub_path="jellystat/data",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="jellystat.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-kapowarr",
    containers=[
        m.Container(
            image="mrcas/kapowarr:latest",
            name="kapowarr",
            ports=[
                m.Port(number=5656, name="web", service_port=6658),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/app/db",
                    storage="none",
                    sub_path="kapowarr/db",
                ),
                m.Volume(
                    name="media-storage",
                    at="/app/temp_downloads",
                    storage="none",
                    sub_path="downloads/kapowarr",
                ),
                m.Volume(
                    name="media-storage",
                    at="/comics",
                    storage="none",
                    sub_path="media/comics",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="kapowarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-lidarr",
    containers=[
        m.Container(
            image="lscr.io/linuxserver/lidarr:latest",
            name="lidarr",
            ports=[
                m.Port(number=8686, name="web", service_port=6656),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="lidarr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/music",
                    storage="none",
                    sub_path="media/music",
                ),
                m.Volume(
                    name="media-storage",
                    at="/downloads",
                    storage="none",
                    sub_path="downloads/lidarr",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="lidarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-profilarr",
    containers=[
        m.Container(
            image="santiagosayshey/profilarr:latest",
            name="profilarr",
            ports=[
                m.Port(number=6868, name="web", service_port=6668),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="profilarr/config",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="profilarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-prowlarr",
    containers=[
        m.Container(
            image="lscr.io/linuxserver/prowlarr:latest",
            name="prowlarr",
            ports=[
                m.Port(number=9696, name="web", service_port=6659),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="prowlarr/config",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="prowlarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-qbittorrent",
    containers=[
        m.Container(
            image="lscr.io/linuxserver/qbittorrent:latest",
            name="qbittorrent",
            ports=[
                m.Port(number=8080, name="web", service_port=6661),
                m.Port(number=6881, name="peer-tcp"),
                m.Port(number=6881, name="peer-udp", proto="UDP"),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="qbittorrent/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/downloads",
                    storage="none",
                    sub_path="downloads/qbittorrent",
                ),
            ],
            env={"WEBUI_PORT": "8080", "TORRENTING_PORT": "6881"},
        ),
    ],
    ingress=m.Ingress(host="qbittorrent.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-radarr",
    containers=[
        m.Container(
            image="lscr.io/linuxserver/radarr:latest",
            name="radarr",
            ports=[
                m.Port(number=7878, name="web", service_port=6654),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="radarr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/movies",
                    storage="none",
                    sub_path="media/movies",
                ),
                m.Volume(
                    name="media-storage",
                    at="/downloads",
                    storage="none",
                    sub_path="downloads/radarr",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="radarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-readarr",
    containers=[
        m.Container(
            image="postgres:alpine",
            name="postgres",
            ports=[m.Port(number=5432)],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/var/lib/postgresql",
                    storage="none",
                    sub_path="readarr/pgdata",
                ),
            ],
            env={
                "POSTGRES_DATABASE": "readarr-glasses",
                "POSTGRES_USER": "readarr-glasses",
            },
        ),
        m.Container(
            image="blampe/rreading-glasses:latest",
            name="readarr",
            ports=[
                m.Port(number=8787, name="web", service_port=6657),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="readarr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/books",
                    storage="none",
                    sub_path="media/books",
                ),
                m.Volume(
                    name="media-storage",
                    at="/downloads",
                    storage="none",
                    sub_path="downloads/readarr",
                ),
            ],
            env={
                "POSTGRES_HOST": "127.0.0.1",
                "POSTGRES_DATABASE": "readarr-glasses",
                "POSTGRES_USER": "readarr-glasses",
            },
        ),
    ],
    ingress=m.Ingress(host="readarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-sonarr",
    containers=[
        m.Container(
            image="lscr.io/linuxserver/sonarr:latest",
            name="sonarr",
            ports=[
                m.Port(number=8989, name="web", service_port=6655),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="sonarr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/tv",
                    storage="none",
                    sub_path="media/tv",
                ),
                m.Volume(
                    name="media-storage",
                    at="/downloads",
                    storage="none",
                    sub_path="downloads/sonarr",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="sonarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-tdarr",
    containers=[
        m.Container(
            image="ghcr.io/haveagitgat/tdarr:latest",
            name="tdarr",
            ports=[
                m.Port(number=8265, name="web", service_port=6663),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/app/server",
                    storage="none",
                    sub_path="tdarr/server",
                ),
                m.Volume(
                    name="media-storage",
                    at="/app/configs",
                    storage="none",
                    sub_path="tdarr/configs",
                ),
                m.Volume(
                    name="media-storage",
                    at="/app/logs",
                    storage="none",
                    sub_path="tdarr/logs",
                ),
                m.Volume(
                    name="media-storage",
                    at="/media",
                    storage="none",
                    sub_path="media",
                ),
                m.Volume(
                    name="media-storage",
                    at="/temp",
                    storage="none",
                    sub_path="tdarr/temp",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="tdarr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-unpackerr",
    containers=[
        m.Container(
            image="golift/unpackerr:latest",
            name="unpackerr",
            ports=[
                m.Port(number=8080, name="web", service_port=6667),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    storage="none",
                    sub_path="unpackerr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/downloads",
                    storage="none",
                    sub_path="downloads/unpackerr",
                ),
            ],
            env={"UNPACKERR_WEB_PORT": "8080"},
        ),
    ],
    ingress=m.Ingress(host="unpackerr.media.dmz.home"),
)

tree.main.folder("media").app(
    name="media-youtarr",
    containers=[
        m.Container(
            image="dialmaster/youtarr:latest",
            name="youtarr",
            ports=[
                m.Port(number=3011, name="web", service_port=6669),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/usr/src/app/data",
                    storage="none",
                    sub_path="media/videos",
                ),
                m.Volume(
                    name="media-storage",
                    at="/app/server/images",
                    storage="none",
                    sub_path="youtarr/images",
                ),
                m.Volume(
                    name="media-storage",
                    at="/app/config",
                    storage="none",
                    sub_path="youtarr/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/app/jobs",
                    storage="none",
                    sub_path="youtarr/jobs",
                ),
            ],
        ),
        m.Container(
            image="mariadb:10.3",
            name="mariadb",
            ports=[m.Port(number=3306)],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/var/lib/mysql",
                    storage="none",
                    sub_path="youtarr/mysql",
                ),
            ],
        ),
    ],
    ingress=m.Ingress(host="youtarr.media.dmz.home"),
)

tree.main.app(
    name="media-jellyfin",
    containers=[
        m.Container(
            image="ghcr.io/jellyfin/jellyfin:latest",
            name="jellyfin",
            ports=[
                m.Port(number=8096, name="web", service_port=6650),
                m.Port(number=8920, name="websecure", service_port=6651),
                m.Port(number=7359, name="dlna"),
            ],
            mounts=[
                m.Volume(
                    name="media-storage",
                    at="/config",
                    size="250Gi",
                    sub_path="jellyfin/config",
                ),
                m.Volume(
                    name="media-storage",
                    at="/cache",
                    size="250Gi",
                    sub_path="jellyfin/cache",
                ),
                m.Volume(
                    name="media-storage",
                    at="/data/media",
                    size="250Gi",
                    sub_path="media",
                ),
            ],
            env={"DOTNET_USE_POLLING_FILE_WATCHER": "1"},
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="jellyfin.media.dmz.home"),
)

tree.main.app(
    name="middleware",
    containers=[],
    options=m.Options(service=False, ingress=False),
)


tree.main.folder("oss").app(
    name="oss-forgejo",
    containers=[
        m.Container(
            image="codeberg.org/forgejo/forgejo:16",
            name="forgejo",
            ports=[
                m.Port(number=3000, service_port=6610),
            ],
            mounts=[
                m.Volume(name="data", at="/data", size="100Gi"),
            ],
            env={
                "FORGEJO__server__DOMAIN": "codeberg.oss.dmz.home",
                "FORGEJO__server__ROOT_URL": "http://codeberg.oss.dmz.home",
                "FORGEJO__server__HTTP_PORT": "3000",
            },
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="codeberg.oss.dmz.home"),
)

tree.main.app(
    name="oss-forgejo",
    containers=[
        m.Container(
            image="codeberg.org/forgejo/forgejo:16",
            name="forgejo",
            ports=[
                m.Port(number=3000, service_port=6610),
            ],
            mounts=[
                m.Volume(name="data", at="/data", size="100Gi"),
            ],
            env={
                "FORGEJO__server__DOMAIN": "codeberg.oss.dmz.home",
                "FORGEJO__server__ROOT_URL": "http://codeberg.oss.dmz.home",
                "FORGEJO__server__HTTP_PORT": "3000",
            },
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="codeberg.oss.dmz.home"),
)
