"""Auto-generated by scan.py — do not edit manually."""
import model as m

tree = m.Tree()

# ══════ main (default ns) ══════


tree.main.folder("code").app(
    name="code-comfyui",
    containers=[
        m.Container(
            image="ghcr.io/lecode-official/comfyui-docker:latest",
            name="comfyui",
            ports=[
                m.Port(number=8188, service_port=4435),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/opt/comfyui/models",
                    size="100Gi",
                    sub_path="models",
                ),
                m.Volume(
                    name="data",
                    at="/opt/comfyui/output",
                    size="100Gi",
                    sub_path="output",
                ),
                m.Volume(
                    name="data",
                    at="/opt/comfyui/custom_nodes",
                    size="100Gi",
                    sub_path="custom_nodes",
                ),
                m.Volume(
                    name="data",
                    at="/opt/comfyui/input",
                    size="100Gi",
                    sub_path="input",
                ),
            ],
            env={"USER_ID": "1000", "GROUP_ID": "1000"},
            mem="8Gi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="comfyui.code.private.home"),
)

tree.main.folder("code").app(
    name="code-n8n",
    containers=[
        m.Container(
            image="n8nio/n8n:latest",
            name="n8n",
            ports=[
                m.Port(number=5678, service_port=4429),
            ],
            mounts=[
                m.Volume(name="data", at="/home/node/.n8n", size="5Gi"),
            ],
            mem="128Mi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="n8n.code.private.home"),
)

tree.main.folder("code").app(
    name="code-odysseus",
    containers=[
        m.Container(
            image="ghcr.io/pewdiepie-archdaemon/odysseus:latest",
            name="odysseus",
            ports=[
                m.Port(number=7000, service_port=4430),
            ],
            mounts=[
                m.Volume(name="data", at="/app/data", size="10Gi"),
                m.Volume(
                    name="data",
                    at="/app/logs",
                    size="10Gi",
                    sub_path="logs",
                ),
                m.Volume(
                    name="data",
                    at="/app/.cache/huggingface",
                    size="10Gi",
                    sub_path="huggingface",
                ),
                m.Volume(
                    name="data",
                    at="/app/.local",
                    size="10Gi",
                    sub_path="local",
                ),
            ],
            mem="256Mi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="odysseus.code.private.home"),
)

tree.main.folder("code").app(
    name="code-ollama",
    containers=[
        m.Container(
            image="ollama/ollama:latest",
            name="ollama",
            ports=[
                m.Port(number=11434, service_port=4431),
            ],
            mounts=[
                m.Volume(name="data", at="/root/.ollama", size="100Gi"),
            ],
            env={"OLLAMA_KEEP_ALIVE": "5m", "OLLAMA_HOST": "0.0.0.0"},
            mem="8Gi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="ollama.code.private.home"),
)

tree.main.folder("code").app(
    name="code-openclaw",
    containers=[
        m.Container(
            image="ghcr.io/openclaw/openclaw:latest",
            name="openclaw",
            ports=[
                m.Port(number=18789, service_port=4432),
                m.Port(number=18790),
            ],
            mounts=[
                m.Volume(
                    name="data",
                    at="/home/node/.openclaw",
                    size="5Gi",
                ),
                m.Volume(
                    name="data",
                    at="/home/node/.openclaw/workspace",
                    size="5Gi",
                    sub_path="workspace",
                ),
            ],
            mem="4Gi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="openclaw.code.private.home"),
)

tree.main.folder("code").app(
    name="code-vscodium",
    containers=[
        m.Container(
            image="codercom/code-server:latest",
            name="vscodium",
            ports=[
                m.Port(number=8080, service_port=4433),
            ],
            mounts=[
                m.Volume(name="data", at="/home/coder", size="10Gi"),
            ],
            env={"DO_NOT_TRACK": "1", "WORKSPACE": "/home/coder/project"},
            mem="8Gi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="vscodium.code.private.home"),
)

tree.main.folder("code").app(
    name="code-webui",
    containers=[
        m.Container(
            image="ghcr.io/open-webui/open-webui:main",
            name="webui",
            ports=[
                m.Port(number=8080, service_port=4434),
            ],
            mounts=[
                m.Volume(name="data", at="/app/backend/data", size="10Gi"),
            ],
            mem="256Mi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="webui.code.private.home"),
)

tree.main.app(
    name="code-ollama",
    containers=[
        m.Container(
            image="ollama/ollama:latest",
            name="ollama",
            ports=[
                m.Port(number=11434, service_port=4431),
            ],
            mounts=[
                m.Volume(name="data", at="/root/.ollama", size="100Gi"),
            ],
            env={"OLLAMA_KEEP_ALIVE": "5m", "OLLAMA_HOST": "0.0.0.0"},
            mem="8Gi",
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="ollama.code.private.home"),
)

tree.main.app(
    name="feed",
    containers=[],
    options=m.Options(service=False, ingress=False),
)

tree.main.app(
    name="gatus",
    containers=[
        m.Container(
            image="twinproduction/gatus:latest",
            ports=[
                m.Port(number=8080, service_port=4401),
            ],
            mounts=[
                m.Config(
                    name="gatus-config",
                    at="/config",
                    file="config.yaml",
                    ro=False,
                ),
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=4400),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
)


tree.main.folder("home").app(
    name="home-homeassistant",
    containers=[
        m.Container(
            image="homeassistant/home-assistant:latest",
            name="homeassistant",
            ports=[
                m.Port(number=8123, service_port=4404),
            ],
            mounts=[
                m.Volume(name="data", at="/config", size="5Gi"),
            ],
            env={"TZ": "Europe/Paris"},
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="homeassistant.home.private.home"),
)

tree.main.app(
    name="home-homeassistant",
    containers=[
        m.Container(
            image="homeassistant/home-assistant:latest",
            name="homeassistant",
            ports=[
                m.Port(number=8123, service_port=4404),
            ],
            mounts=[
                m.Volume(name="data", at="/config", size="5Gi"),
            ],
            env={"TZ": "Europe/Paris"},
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="homeassistant.home.private.home"),
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=4401),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
)

tree.main.app(
    name="middleware",
    containers=[],
    options=m.Options(service=False, ingress=False),
)


tree.main.folder("monitor").app(
    name="monitor-dozzle",
    containers=[
        m.Container(
            image="amir20/dozzle:latest",
            name="dozzle",
            ports=[
                m.Port(number=8080, service_port=4415),
            ],
            mounts=[
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
            env={
                "DOZZLE_MODE": "k8s",
                "DOZZLE_ALL_NAMESPACES": "true",
                "DOZZLE_LEVEL": "info",
            },
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="dozzle.monitor.private.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                resources=["pods", "pods/log", "nodes"],
            ),
            m.PolicyRule(
                verbs=["get", "list"],
                api_groups=["metrics.k8s.io"],
                resources=["pods"],
            ),
        ],
    ),
)

tree.main.folder("monitor").app(
    name="monitor-grafana",
    containers=[
        m.Container(
            image="grafana/grafana:latest",
            name="grafana",
            ports=[
                m.Port(number=3000, service_port=4421),
            ],
            mounts=[
                m.Volume(name="data", at="/var/lib/grafana", size="5Gi"),
            ],
            env={
                "GF_SERVER_ROOT_URL": "http://grafana.monitor.private.home",
                "GF_PLUGINS_PREINSTALL": "grafana-clock-panel",
            },
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="grafana.monitor.private.home"),
)

tree.main.folder("monitor").app(
    name="monitor-headlamp",
    containers=[
        m.Container(
            image="ghcr.io/headlamp-k8s/headlamp:latest",
            name="headlamp",
            ports=[
                m.Port(number=8080, service_port=4420),
            ],
            mounts=[
                m.Volume(name="data", at="/headlamp/config", size="1Gi"),
            ],
            env={"HEADLAMP_CLUSTER_NAME": "my-cluster"},
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="headlamp.monitoring.private.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(verbs=["get", "list", "watch"], resources=["*"]),
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                api_groups=[
                    "apps",
                    "batch",
                    "extensions",
                    "networking.k8s.io",
                    "rbac.authorization.k8s.io",
                ],
                resources=["*"],
            ),
            m.PolicyRule(
                verbs=["get", "list"],
                api_groups=["metrics.k8s.io"],
                resources=["pods"],
            ),
        ],
    ),
)

tree.main.folder("monitor").app(
    name="monitor-prometheus",
    containers=[
        m.Container(
            image="prom/prometheus:latest",
            name="prometheus",
            ports=[
                m.Port(number=9090, service_port=4422),
            ],
            mounts=[
                m.Volume(name="data", at="/prometheus", size="10Gi"),
                m.Config(
                    name="prometheus-config",
                    at="/etc/prometheus/prometheus.yaml",
                    file="prometheus.yaml",
                    ro=False,
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="prometheus.monitor.private.home"),
)

tree.main.app(
    name="monitor-dozzle",
    containers=[
        m.Container(
            image="amir20/dozzle:latest",
            name="dozzle",
            ports=[
                m.Port(number=8080, service_port=4420),
            ],
            mounts=[
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
            env={
                "DOZZLE_MODE": "k8s",
                "DOZZLE_ALL_NAMESPACES": "true",
                "DOZZLE_LEVEL": "info",
            },
        ),
    ],
    options=m.Options(storage="cephfs"),
    ingress=m.Ingress(host="dozzle.monitor.private.home"),
    service_account=m.ServiceAccount(
        rules=[
            m.PolicyRule(
                verbs=["get", "list", "watch"],
                resources=["pods", "pods/log", "nodes"],
            ),
            m.PolicyRule(
                verbs=["get", "list"],
                api_groups=["metrics.k8s.io"],
                resources=["pods"],
            ),
        ],
    ),
)

tree.main.app(
    name="tool",
    containers=[],
    options=m.Options(service=False, ingress=False),
)
