"""Auto-generated by scan.py — do not edit manually."""
import model as m

tree = m.Tree()

# ══════ main (default ns) ══════

tree.main.app(
    name="gatus",
    containers=[
        m.Container(
            image="twinproduction/gatus:latest",
            ports=[
                m.Port(number=8080, service_port=9901),
            ],
            mounts=[
                m.Config(
                    name="gatus-config",
                    at="/config",
                    file="config.yaml",
                    ro=False,
                ),
                m.Volume(name="data", at="/data", size="1Gi"),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=9900),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
)

tree.main.app(
    name="glance",
    containers=[
        m.Container(
            image="glanceapp/glance:latest",
            ports=[
                m.Port(number=8080, service_port=9901),
            ],
            mounts=[
                m.Config(
                    name="glance-config",
                    at="/app/config/",
                    file="config.yaml",
                ),
            ],
        ),
    ],
    options=m.Options(storage="cephfs"),
)

tree.main.app(
    name="middleware",
    containers=[],
    options=m.Options(service=False, ingress=False),
)
