# Full reference: https://github.com/iv-org/invidious/blob/master/config/config.example.yml

db:
  dbname: invidious
  user: kemal
  password: CHANGEME_same_secret.env
  host: 127.0.0.1
  port: 5432
  check_tables: true
domain: invidious.alt.dmz.home
# trust Traefik's X-Forwarded-Proto instead of serving TLS itself
https_only: false
external_port: 443
# e.g. `openssl rand -hex 32`
hmac_key: CHANGEME_random
invidious_companion:
  - private_url: http://127.0.0.1:8282/companion
    public_url: https://invidious.alt.dmz.home/companion
invidious_companion_key: CHANGEME_same_secret.env
# flip to true if you want others to sign up
registration_enabled: false
statistics_enabled: false
