apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: immich-
namespace: dmz

resources:
  - service-account.yaml
  - pvc.yaml
  - pv.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: immich-config
    envs:
      - config.env

secretGenerator:
  - name: immich-secret
    envs:
      - secret.env
    type: Opaque
