apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-dmz

resources:
  - ../../../base/dmz

patches:
  - target:
      kind: ".*"      # applies to all kinds
    patch: |
      - op: replace
        path: /metadata/namespace
        value: dev-dmz