apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: harbor-
namespace: default
# | Service         | Port(s)     | Notes                          |
# | :---            | :---        | :---                           |
# | core            | 8080 / 8443 | HTTP / HTTPS (likely)          |
# | registry        | 5000        | Container image registry API   |
# | registryctl     | 8081        | Registry control service       |
# | jobservice      | 8082        | Job processing service         |
# | trivy-adapter   | 8083        | Vulnerability scanning adapter |
# | portal          | 8090        | Web UI frontend                |
# | exporter        | 8001        | Default port, untouched        |
# | metric          | 8085        | metric endpoint prometheus     |
# | log (rsyslog)   | 1514        | System/logging service         |
# | postgresql      | 5432        | Database                       |
# | redis / valkey  | 6379        | In-memory cache / broker       |
resources:
  - sa.yaml
  - cluster-role.yaml
  - cluster-role-binding.yaml
  - pvc-cephfs.yaml
  - pv-cephfs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - daemonset.yaml
  - configmaps.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: harbor-config
    envs:
      - config.env
# - name: harbor-trust-certs
#   files:
#     - ca.crt
#     # Add more CA files here as needed, e.g. another 'ca2.crt' line —
#     # each becomes its own key in the ConfigMap by filename.

secretGenerator:
  - name: harbor-secret
    envs:
      - secret.env
    type: Opaque
  - name: core-private-key
    files:
      - private_key.pem
  - name: registry-root-crt
    files:
      - root.crt
  - name: core-secretkey
    files:
      - secretkey
