apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: default
  labels:
    app: main-harbor
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # cephfs
  # mountOptions:
  #   - nolock
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeHandle: cephfs-vicus-default-harbor
    volumeAttributes:
      clusterID: rook-ceph
      fsName: bhole
      staticVolume: "true"
      rootPath: /volumes/colosseum/vicus-default/effbd7ff-fd15-4e5a-93a2-4be7039fb06b/harbor/
