apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: default
  labels:
    app: main-harbor
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
    # - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.24  # your NFS server IP
    path: /bhole/cluster/main/harbor/ # your NFS export path