apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: private
  labels:
    app: private-openclaw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-openclaw
  template:
    metadata:
      labels:
        app: private-openclaw
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      serviceAccountName: serviceaccount
      containers:
        - name: openclaw
          image: ghcr.io/openclaw/openclaw:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          ports:
            - containerPort: 18789   # Gateway UI/API[reference:5]
            - containerPort: 18790   # Bridge[reference:6]
            # like yeah i could do the cli and browser too
          envFrom:
          - configMapRef:
              name: openclaw-config
          resources:
            requests:
              memory: "4Gi"
            limits:
              memory: "8Gi"
          volumeMounts:
            - name: data
              mountPath: /home/node/.openclaw          # Config, canvas, cron[reference:10]
            - name: data
              mountPath: /home/node/.openclaw/workspace
              subPath: workspace
          livenessProbe:
            httpGet:
              path: /health
              port: 18789
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 18789
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc