apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: dmz
  labels:
    app: dmz-media-jellystat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dmz-media-jellystat
  template:
    metadata:
      labels:
        app: dmz-media-jellystat
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10

      # Ensure PostgreSQL user (uid 999) can write to PVC
      securityContext:
        fsGroup: 999

      initContainers:
        # --- postgres sidecar ---
        - name: postgres
          image: postgres:18-alpine
          imagePullPolicy: IfNotPresent
          # Setting restartPolicy: Always makes this a sidecar container.
          restartPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: jellystat-config
            - secretRef:
                name: jellystat-secret
          volumeMounts:
            - name: media-storage
              mountPath: /var/lib/postgresql
              subPath: jellystat/pgdata
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - jellystat
            initialDelaySeconds: 5
            periodSeconds: 2

      containers:
        # --- Jellystat Main ---
        - name: jellystat
          image: ghcr.io/cyfershepard/jellystat:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          ports:
            - containerPort: 3001
              name: web
          envFrom:
            - configMapRef:
                name: jellystat-config
            - secretRef:
                name: jellystat-secret
          volumeMounts:
            - name: media-storage
              mountPath: /app/backend/data
              subPath: jellystat/data

      volumes:
        - name: media-storage
          persistentVolumeClaim:
            claimName: media-pvc