apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: jellystat-
namespace: dmz

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: jellystat-config
    envs:
      - config.env

secretGenerator:
  - name: jellystat-secret
    envs:
      - secret.env
    type: Opaque

generatorOptions:
  disableNameSuffixHash: true