storage:
  type: sqlite
  path: /data/data.db

metrics: true

endpoints:
  - name: glance
    url: "http://public-glance-service.public.svc.cluster.local:9900"
    interval: 30s
    conditions:
      - "[STATUS] == 200"

  - name: gatus
    url: "http://public-gatus-service.public.svc.cluster.local:9901"
    interval: 30s
    conditions:
      - "[STATUS] == 200"