apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  namespace: public
  labels:
    app: public-gatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: public-gatus
  template:
    metadata:
      labels:
        app: public-gatus
    spec:
      tolerations:
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 10
      serviceAccountName: serviceaccount
      containers:
        - name: gatus
          image: twinproduction/gatus:latest
          imagePullPolicy: IfNotPresent
          # restartPolicy: Always
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /data
              # readinessProbe:
              #   httpGet:
              #     path: /
              #     port: 80
              #   initialDelaySeconds: 5
              #   periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: gatus-config
        - name: data
          persistentVolumeClaim:
            claimName: data-pvc
