apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: public
  labels:
    app: public-gatus
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
    # - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.24 # your NFS server IP
    path: /bhole/cluster/public/gatus/ # your NFS export path
