apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: public
  labels:
    app: public-gatus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeName: pv
  resources:
    requests:
      storage: 1Gi
