apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: openwrt-
namespace: default
resources:
  - sa.yaml
  - multus-config.yaml
  - pv-cephfs.yaml
  - pvc-cephfs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
