apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: default
  labels:
    app: main-openwrt
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
    - ReadWriteMany
    # - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.1.24
    path: /bhole/cluster/default/openwrt/
