apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: private
  labels:
    app: private-code-webui
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # cephfs
  # mountOptions:
  #   - nolock
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeHandle: cephfs-vicus-private-code-webui
    volumeAttributes:
      clusterID: rook-ceph
      fsName: bhole
      staticVolume: "true"
      rootPath: /volumes/k8s-colosseum/vicus-private/c8e734df-e422-4b77-8ab5-ef8ece645e26/code/webui/
