# apiVersion: v1
# kind: Namespace
# metadata:
#   name: default
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-public
  labels:
    environment: prod
    zone: public
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-dmz
  labels:
    environment: prod
    zone: dmz
---
apiVersion: v1
kind: Namespace
metadata:
  name: prod-private
  labels:
    environment: prod
    zone: private