apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: private
  labels:
    app: private-odysseus
spec:
  type: ClusterIP
  selector:
    app: private-odysseus
  ports:
    - name: web
      protocol: TCP
      port: 4430
      targetPort: 7000