apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prometheus-
namespace: private
resources:
  - pvc-cephfs.yaml
  - pv-cephfs.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sa.yaml
configMapGenerator:
  - name: prometheus-config
    files:
      - prometheus.yaml
