apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  namespace: private
  labels:
    app: private-monitor-prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # cephfs
  # mountOptions:
  #   - nolock
  csi:
    driver: rook-ceph.cephfs.csi.ceph.com
    nodeStageSecretRef:
      name: rook-csi-cephfs-node
      namespace: rook-ceph
    volumeHandle: cephfs-vicus-private-monitor-prometheus
    volumeAttributes:
      clusterID: rook-ceph
      fsName: bhole
      staticVolume: "true"
      rootPath: /volumes/colosseum/vicus-private/4a6c2f11-9025-429e-adc6-80f3f029c43e/monitor/prometheus/
