# cp 02-kustomization.yaml kustomization.yaml
# kubectl apply -k .
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install-edge | sh
resources:
  # Traefik CRDs + RBAC
  # https://doc.traefik.io/traefik/reference/install-configuration/providers/kubernetes/kubernetes-crd/
  - https://raw.githubusercontent.com/traefik/traefik/v3.7/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  - https://raw.githubusercontent.com/traefik/traefik/v3.7/docs/content/reference/dynamic-configuration/kubernetes-crd-rbac.yml
  # metrics.k8s.io API + metrics-server, needed for `kubectl top` (used by dozzle and prometheus)
  - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
  # Volcano gang scheduler
  # https://volcano.sh/docs/GettingStarted/Installation
  - https://raw.githubusercontent.com/volcano-sh/volcano/master/installer/volcano-development.yaml
  # spinkube wasm/wasi pod sheduler
  # https://github.com/spinframework/spin-operator/releases/
  - ../spinkube
  # KubeVirt operator VMs
  # https://kubevirt.io/user-guide/cluster_admin/installation/
  # https://github.com/kubevirt/kubevirt/releases/tag/v1.9.0
  - https://github.com/kubevirt/kubevirt/releases/download/v1.9.0/kubevirt-operator.yaml
  # Rook-Ceph operator + its CRDs/RBAC/CSI operator
  # https://rook.github.io/docs/rook/latest-release/Getting-Started/quickstart/
  # https://github.com/rook/rook/releases/tag/v1.20.2
  - https://raw.githubusercontent.com/rook/rook/v1.20.2/deploy/examples/crds.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.20.2/deploy/examples/common.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.20.2/deploy/examples/common-external.yaml
  - https://raw.githubusercontent.com/rook/rook/v1.20.2/deploy/examples/networkpolicy.yaml
  # github.com/squat/generic-device-plugin
  - https://raw.githubusercontent.com/squat/generic-device-plugin/main/manifests/generic-device-plugin.yaml
  # https://kittizz.github.io/cert-manager-technitium-webhook/

  # idk linkerd 
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/standard-install.yaml

  # nvidia gpu runtime
  - ../nvidia
# TODO : patch here for generic-device-plugin --device

