apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: private
  labels:
    app: private-monitor-dozzle
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "" # cephfs
  volumeName: pv
  resources:
    requests:
      storage: 1Gi
